language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - hhvm

matrix:
  allow_failures:
    - php: 7.4
    - php: hhvm
  fast_finish: true

install:
  - composer install

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
